var attributes = {
    "hair": [
        'Afro',
        'Asymetrical Cut',
        'Beehive',
        'Bangs',
        'Bob Cut',
        'Bouffant',
        'Bowl Cut',
        'Braids',
        'Bun',
        'Pigtails',
        'Butch',
        'Business',
        'Buzz Cut',
        'Ceasar Cut',
        'Tonsure',
        'Comb Over',
        'Conk',
        'Cornrows',
        'Crew Cut',
        'Cropped Hair',
        'Curtained',
        'Devilock',
        'Dido Flip',
        'Dreadlocks',
        'D.A.',
        'Fauxhawk',
        'Feather Cut',
        'Feathered Hair',
        'Flattop',
        'French Braid',
        'French Twist',
        'Fringe',
        'Frosted Tips',
        'Highlights',
        'Hime Cut',
        'Ivy League',
        'Jewfro',
        'Liberty Spikes',
        'Long Hair',
        'Marcelling',
        'Mohawk',
        'Mop-Top',
        'Mullet',
        'Odango',
        'Pageboy',
        'Payot',
        'Perm',
        'Pixie Cut',
        'Pompadour',
        'Ponyhawk',
        'Pony Tail',
        'Quiff',
        'Rattail',
        'Shag',
        'Short Hair',
        'Slicked-Back',
        'Spiky Hair',
        'Surfer',
        'Tail',
        'Tonsure',
        'Undercut',
        'Updo',
        'Waves',
        'Wings'
    ],
    "job": [
        'Actor',
        'Alchemist',
        'Animator',
        'Apprentice',
        'Archaeologist',
        'Architect',
        'Artificer',
        'Artisan',
        'Artist',
        'Assassin',
        'Assistant',
        'Astronaught',
        'Astronomer',
        'Author',
        'Barbarian',
        'Bard',
        'Bartender',
        'Biologist',
        'Blacksmith',
        'Blogger',
        'Book Maker',
        'Botanist',
        'Bounty Hunter',
        'Breeder',
        'Brewer',
        'Buttler',
        'Carpenter',
        'Cartographer',
        'Cartoonist',
        'Cashier',
        'Charlatan',
        'Chemist',
        'Cleric',
        'Coder',
        'Conductor',
        'Construction Worker',
        'Cook',
        'Counselor',
        'Critic',
        'Dancer',
        'Dentist',
        'Director',
        'Doctor',
        'Driver',
        'Druid',
        'Dump Truck Driver',
        'Electrician',
        'Enchanter',
        'Engineer',
        'Factory Worker',
        'Farmer',
        'Fighter',
        'Fire Fighter',
        'Fisher',
        'Flameworker',
        'Foreman',
        'Freelance Artist',
        'Furry',
        'Fursuit Maker',
        'Garbage Truck Driver',
        'Geek',
        'Geographer',
        'Geologist',
        'Gladiator',
        'Glassblower',
        'Graphic Designer',
        'Gunsmith',
        'Hacker',
        'Herbalist',
        'Hunter',
        'Hypnotist',
        'Inn Keeper',
        'Inquisitor',
        'Janitor',
        'Jeweler',
        'Journalist',
        'Junk Yard Owner',
        'Knight',
        'Laborer',
        'Lawyer',
        'Leatherworker',
        'Librarian',
        'Lord',
        'Mage',
        'Maid',
        'Marine',
        'Martial Artist',
        'Mason',
        'Mathmatician',
        'Mechanic',
        'Medic',
        'Merchant',
        'Miner',
        'Monk',
        'Muscian',
        'Mystic',
        'Necromancer',
        'Nerd',
        'Newscaster',
        'Ninja',
        'Nurse',
        'Officer',
        'Oracle',
        'Painter',
        'Paladin',
        'Physicist',
        'Pilot',
        'Pirate',
        'Police Officer',
        'Potter',
        'Priest',
        'Professional Alcoholic',
        'Psychiatrist',
        'Psychologist',
        'Ranger',
        'Researcher',
        'Reviewer',
        'Rider',
        'Rogue',
        'Sailor',
        'Samurai',
        'Savage',
        'Scholar',
        'Scientist',
        'Scout',
        'Scoutmaster',
        'Screenwriter',
        'Sculptor',
        'Shaman',
        'Solider',
        'Sorceror',
        'Spy',
        'Stage Magician',
        'Steampunk',
        'Store Owner',
        'Summoner',
        'Supervisor',
        'Surgeon',
        'Tailor',
        'Tamer',
        'Taxidermist',
        'Teacher',
        'Technician',
        'Techromancer',
        'Tinker',
        'Traveling Salesman',
        'Truck Driver',
        'Usher',
        'Vigilante',
        'Voice Actor',
        'Waiter',
        'Warlock',
        'Warlord',
        'Warrior',
        'Weatherman',
        'Weaver',
        'Welder',
        'Witch Hunter',
        'Witch',
        'Wizard',
        'Writer',
        'YouTuber',
        'Zoologist'
    ],
    "species": [
        'Aardvark',
        'Abyssinian',
        'Adelie Penguin',
        'Affenpinscher',
        'Afghan Hound',
        'African Bush Elephant',
        'African Civet',
        'African Clawed Frog',
        'African Forest Elephant',
        'African Palm Civet',
        'African Penguin',
        'African Tree Toad',
        'African Wild Dog',
        'Ainu Dog',
        'Airedale Terrier',
        'Akbash',
        'Akita',
        'Alaskan Malamute',
        'Albatross',
        'Aldabra Giant Tortoise',
        'Alicorn',
        'Alligator',
        'Allosaurus',
        'Alpine Dachsbracke',
        'American Bulldog',
        'American Cocker Spaniel',
        'American Coonhound',
        'American Eskimo Dog',
        'American Foxhound',
        'American Pit Bull Terrier',
        'American Staffordshire Terrier',
        'American Water Spaniel',
        'Anatolian Shepherd Dog',
        'Angel',
        'Angelfish',
        'Ankylosaur',
        'Ant',
        'Anteater',
        'Antelope',
        'Anubus',
        'Appenzeller Dog',
        'Arctic Fox',
        'Arctic Hare',
        'Arctic Wolf',
        'Armadillo',
        'Asian Elephant',
        'Asian Giant Hornet',
        'Asian Palm Civet',
        'Asiatic Black Bear',
        'Australian Cattle Dog',
        'Australian Kelpie Dog',
        'Australian Mist',
        'Australian Shepherd',
        'Australian Terrier',
        'Avocet',
        'Axolotl',
        'Aye Aye',
        'Baboon',
        'Bactrian Camel',
        'Badger',
        'Balinese',
        'Banded Palm Civet',
        'Bandicoot',
        'Barb',
        'Barn Owl',
        'Barnacle',
        'Barracuda',
        'Basenji Dog',
        'Basilisk',
        'Basking Shark',
        'Basset Hound',
        'Bat',
        'Bavarian Mountain Hound',
        'Beagle',
        'Bear',
        'Bearded Collie',
        'Bearded Dragon',
        'Beaver',
        'Bedlington Terrier',
        'Beetle',
        'Bengal Tiger',
        'Bernese Mountain Dog',
        'Bichon Frise',
        'Binturong',
        'Bird',
        'Birds Of Paradise',
        'Birman',
        'Bison',
        'Black Bear',
        'Black Rhinoceros',
        'Black Russian Terrier',
        'Black Widow Spider',
        'Bloodhound',
        'Blue Lacy Dog',
        'Blue Whale',
        'Bluetick Coonhound',
        'Bobcat',
        'Bolognese Dog',
        'Bombay',
        'Bongo',
        'Bonobo',
        'Booby',
        'Border Collie',
        'Border Terrier',
        'Bornean Orang-utan',
        'Borneo Elephant',
        'Boston Terrier',
        'Bottle Nosed Dolphin',
        'Boxer Dog',
        'Boykin Spaniel',
        'Brachiosaurus',
        'Brazilian Terrier',
        'Brontosaurus',
        'Brown Bear',
        'Budgerigar',
        'Buffalo',
        'Bull Mastiff',
        'Bull Shark',
        'Bull Terrier',
        'Bulldog',
        'Bullfrog',
        'Bumble Bee',
        'Burmese',
        'Burrowing Frog',
        'Butterfly Fish',
        'Butterfly',
        'Caiman Lizard',
        'Caiman',
        'Cairn Terrier',
        'Camel',
        'Canaan Dog',
        'Capybara',
        'Caracal',
        'Carolina Dog',
        'Cassowary',
        'Cat',
        'Caterpillar',
        'Catfish',
        'Cavalier King Charles Spaniel',
        'Centaur',
        'Centipede',
        'Cerberus',
        'Cesky Fousek',
        'Chameleon',
        'Chamois',
        'Cheetah',
        'Chesapeake Bay Retriever',
        'Chicken',
        'Chihuahua',
        'Chimera',
        'Chimpanzee',
        'Chinchilla',
        'Chinese Crested Dog',
        'Chinook',
        'Chinstrap Penguin',
        'Chipmunk',
        'Chow Chow',
        'Cichlid',
        'Clouded Leopard',
        'Clown Fish',
        'Clumber Spaniel',
        'Coati',
        'Cockatrice',
        'Cockroach',
        'Collared Peccary',
        'Collie',
        'Common Buzzard',
        'Common Frog',
        'Common Loon',
        'Common Toad',
        'Coral',
        'Cottontop Tamarin',
        'Cougar',
        'Cow',
        'Coyote',
        'Crab-Eating Macaque',
        'Crab',
        'Crane',
        'Crested Penguin',
        'Crocodile',
        'Cross River Gorilla',
        'Curly Coated Retriever',
        'Cuscus',
        'Cuttlefish',
        'Dachshund',
        'Dalmatian',
        'Darwins Frog',
        'Deer',
        'Demon',
        'Desert Tortoise',
        'Deutsche Bracke',
        'Dhole',
        'Dingo',
        'Dinosaur',
        'Discus',
        'Doberman Pinscher',
        'Dodo',
        'Dog',
        'Dogo Argentino',
        'Dogue De Bordeaux',
        'Dolphin',
        'Donkey',
        'Dormouse',
        'Dragon',
        'Dragonfly',
        'Drever',
        'Duck',
        'Dugong',
        'Dunker',
        'Dusky Dolphin',
        'Dwarf Crocodile',
        'Eagle',
        'Earwig',
        'Eastern Gorilla',
        'Eastern Lowland Gorilla',
        'Echidna',
        'Edible Frog',
        'Egyptian Mau',
        'Electric Eel',
        'Elephant Seal',
        'Elephant Shrew',
        'Elephant',
        'Emperor Penguin',
        'Emperor Tamarin',
        'Emu',
        'English Cocker Spaniel',
        'English Shepherd',
        'English Springer Spaniel',
        'Entlebucher Mountain Dog',
        'Epagneul Pont Audemer',
        'Eskimo Dog',
        'Estrela Mountain Dog',
        'Fairy',
        'Falcon',
        'Fennec Fox',
        'Ferret',
        'Field Spaniel',
        'Fin Whale',
        'Finnish Spitz',
        'Fire-Bellied Toad',
        'Fish',
        'Fishing Cat',
        'Flamingo',
        'Flat Coat Retriever',
        'Flounder',
        'Fly',
        'Flying Squirrel',
        'Fossa',
        'Fox Terrier',
        'Fox',
        'French Bulldog',
        'Frigatebird',
        'Frilled Lizard',
        'Frog',
        'Fur Seal',
        'Galapagos Penguin',
        'Galapagos Tortoise',
        'Gar',
        'Gecko',
        'Gentoo Penguin',
        'Geoffroys Tamarin',
        'Gerbil',
        'German Pinscher',
        'German Shepherd',
        'Gharial',
        'Giant African Land Snail',
        'Giant Clam',
        'Giant Panda Bear',
        'Giant Schnauzer',
        'Gibbon',
        'Gila Monster',
        'Giraffe',
        'Glass Lizard',
        'Glow Worm',
        'Goat',
        'Golden Lion Tamarin',
        'Golden Oriole',
        'Golden Retriever',
        'Goose',
        'Gopher',
        'Gorilla',
        'Grasshopper',
        'Great Dane',
        'Great White Shark',
        'Greater Swiss Mountain Dog',
        'Green Bee-Eater',
        'Greenland Dog',
        'Grey Mouse Lemur',
        'Grey Reef Shark',
        'Grey Seal',
        'Greyhound',
        'Grizzly Bear',
        'Grouse',
        'Gryphon',
        'Guinea Fowl',
        'Guinea Pig',
        'Guppy',
        'Hadrosaur',
        'Hammerhead Shark',
        'Hamster',
        'Hare',
        'Harrier',
        'Havanese',
        'Hedgehog',
        'Hercules Beetle',
        'Hermit Crab',
        'Heron',
        'Highland Cattle',
        'Hippogripsh',
        'Hippopotamus',
        'Honey Bee',
        'Horn Shark',
        'Horned Frog',
        'Horse',
        'Horseshoe Crab',
        'Howler Monkey',
        'Human',
        'Humboldt Penguin',
        'Hummingbird',
        'Humpback Whale',
        'Hydra',
        'Hyena',
        'Ibis',
        'Ibizan Hound',
        'Iguana',
        'Impala',
        'Indian Elephant',
        'Indian Palm Squirrel',
        'Indian Rhinoceros',
        'Indian Star Tortoise',
        'Indochinese Tiger',
        'Indri',
        'Insect',
        'Irish Setter',
        'Irish WolfHound',
        'Jack Russel',
        'Jackal',
        'Jackalope',
        'Jaguar',
        'Japanese Chin',
        'Japanese Macaque',
        'Javan Rhinoceros',
        'Javanese',
        'Jellyfish',
        'Kakapo',
        'Kangaroo',
        'Keel Billed Toucan',
        'Killer Whale',
        'King Crab',
        'King Penguin',
        'Kingfisher',
        'Kiwi',
        'Koala',
        'Komodo Dragon',
        'Kudu',
        'Labradoodle',
        'Labrador Retriever',
        'Ladybird',
        'Leaf-Tailed Gecko',
        'Lemming',
        'Lemur',
        'Leopard Cat',
        'Leopard Seal',
        'Leopard Tortoise',
        'Leopard',
        'Liger',
        'Lion',
        'Lionfish',
        'Little Penguin',
        'Lizard',
        'Llama',
        'Lobster',
        'Long-Eared Owl',
        'Lynx',
        'Macaroni Penguin',
        'Macaw',
        'Magellanic Penguin',
        'Magpie',
        'Maine Coon',
        'Malayan Civet',
        'Malayan Tiger',
        'Maltese',
        'Manatee',
        'Mandrill',
        'Manta Ray',
        'Manticore',
        'Marine Toad',
        'Markhor',
        'Marsh Frog',
        'Masked Palm Civet',
        'Mastiff',
        'Mayfly',
        'Meerkat',
        'Millipede',
        'Minke Whale',
        'Minotaur',
        'Mocking Bird',
        'Mole',
        'Molly',
        'Mongoose',
        'Mongrel',
        'Monitor Lizard',
        'Monkey',
        'Monte Iberia Eleuth',
        'Moorhen',
        'Moose',
        'Moray Eel',
        'Moth',
        'Mountain Gorilla',
        'Mountain Lion',
        'Mouse',
        'Mule',
        'Neanderthal',
        'Neapolitan Mastiff',
        'Newfoundland',
        'Newt',
        'Nightingale',
        'Norfolk Terrier',
        'Norwegian Forest',
        'Numbat',
        'Nurse Shark',
        'Ocelot',
        'Octopus',
        'Okapi',
        'Old English Sheepdog',
        'Olm',
        'Opossum',
        'Orang-utan',
        'Ostrich',
        'Otter',
        'Oyster',
        'Pademelon',
        'Panther',
        'Parrot',
        'Patas Monkey',
        'Peacock',
        'Pegasus',
        'Pekingese',
        'Pelican',
        'Penguin',
        'Persian',
        'Pheasant',
        'Phoenix',
        'Pied Tamarin',
        'Pig',
        'Pika',
        'Pike',
        'Pink Fairy Armadillo',
        'Piranha',
        'Platypus',
        'Pointer',
        'Poison Dart Frog',
        'Polar Bear',
        'Pond Skater',
        'Poodle',
        'Pool Frog',
        'Porcupine',
        'Possum',
        'Prawn',
        'Proboscis Monkey',
        'Puffer Fish',
        'Puffin',
        'Pug',
        'Puma',
        'Purple Emperor',
        'Puss Moth',
        'Pygmy Hippopotamus',
        'Pygmy Marmoset',
        'Quail',
        'Quetzal',
        'Quokka',
        'Quoll',
        'Rabbit',
        'Raccoon Dog',
        'Raccoon',
        'Radiated Tortoise',
        'Ragdoll',
        'Raptor',
        'Rat',
        'Rattlesnake',
        'Red Knee Tarantula',
        'Red Panda',
        'Red Wolf',
        'Red-handed Tamarin',
        'Reindeer',
        'Rhinoceros',
        'River Dolphin',
        'River Turtle',
        'Robin',
        'Rock Hyrax',
        'Rockhopper Penguin',
        'Roseate Spoonbill',
        'Rottweiler',
        'Royal Penguin',
        'Russian Blue',
        'Sabre-Toothed Tiger',
        'Saint Bernard',
        'Salamander',
        'Sand Lizard',
        'Saola',
        'Satyr',
        'Sauropods',
        'Scorpion Fish',
        'Scorpion',
        'Sea Dragon',
        'Sea Lion',
        'Sea Otter',
        'Sea Slug',
        'Sea Squirt',
        'Sea Turtle',
        'Sea Urchin',
        'Seahorse',
        'Seal',
        'Serval',
        'Shape Shifter',
        'Sheep',
        'Shih Tzu',
        'Shrimp',
        'Siamese Fighting Fish',
        'Siamese',
        'Siberian Husky',
        'Siberian Tiger',
        'Siberian',
        'Silver Dollar',
        'Skunk',
        'Sloth',
        'Slow Worm',
        'Snail',
        'Snake',
        'Snapping Turtle',
        'Snowshoe',
        'Snowy Owl',
        'Somali',
        'South China Tiger',
        'Spadefoot Toad',
        'Sparrow',
        'Spectacled Bear',
        'Sperm Whale',
        'Sphinx',
        'Spider Monkey',
        'Spinosaurus',
        'Spiny Dogfish',
        'Sponge',
        'Squid',
        'Squirrel Monkey',
        'Squirrel',
        'Sri Lankan Elephant',
        'Staffordshire Bull Terrier',
        'Stag Beetle',
        'Starfish',
        'Stegosaurus',
        'Stellers Sea Cow',
        'Stick Insect',
        'Stingray',
        'Stoat',
        'Striped Rocket Frog',
        'Sumatran Elephant',
        'Sumatran Orang-utan',
        'Sumatran Rhinoceros',
        'Sumatran Tiger',
        'Sun Bear',
        'Swan',
        'Tang',
        'Tapir',
        'Tarsier',
        'Tasmanian Devil',
        'Taur',
        'Tawny Owl',
        'Termite',
        'Tetra',
        'Thorny Devil',
        'Tibetan Mastiff',
        'Tiger Salamander',
        'Tiger Shark',
        'Tiger',
        'Tortoise',
        'Toucan',
        'Tree Frog',
        'Triceratops',
        'Tropicbird',
        'Tuatara',
        'Turkey',
        'Turkish Angora',
        'Tyrannosaur',
        'Uakari',
        'Uguisu',
        'Umbrellabird',
        'Unicorn',
        'Vampire Bat',
        'Vervet Monkey',
        'Vulture',
        'Wallaby',
        'Walrus',
        'Warthog',
        'Wasp',
        'Water Buffalo',
        'Water Dragon',
        'Water Vole',
        'Weasel',
        'Welsh Corgi',
        'Were',
        'Werewolf',
        'West Highland Terrier',
        'Western Gorilla',
        'Western Lowland Gorilla',
        'Whale Shark',
        'Whippet',
        'White Faced Capuchin',
        'White Rhinoceros',
        'White Tiger',
        'Wild Boar',
        'Wildebeest',
        'Wolf',
        'Wolverine',
        'Wombat',
        'Woodlouse',
        'Woodpecker',
        'Woolly Mammoth',
        'Woolly Monkey',
        'Wrasse',
        'X-Ray Tetra',
        'Yak',
        'Yellow-Eyed Penguin',
        'Yorkshire Terrier',
        'Zebra Shark',
        'Zebra',
        'Zebu',
        'Zonkey',
        'Zorse'
    ]
}
